apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fencer-db
spec:
  serviceName: "fencer-db"
  replicas: 1
  selector:
    matchLabels:
      app: fencer-db
  template:
    metadata:
      labels:
        app: fencer-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fencer-db-secret
                  key: FENCER_DB_PASSWORD
            - name: POSTGRES_DB
              value: safetrace_fencer
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
