services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  auth-db:
    image: postgres:15
    container_name: auth-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: safetrace
      POSTGRES_DB: safetrace_auth
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  fencer-db:
    image: postgres:15
    container_name: fencer-db
    ports:
      - "5434:5434"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: safetrace
      POSTGRES_DB: safetrace_fencer
    volumes:
      - fencer_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  auth_pgdata:
  fencer_pgdata:
