apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  AUTH_PORT: "3001"
  AUTH_DB_HOST: auth-db
  AUTH_DB_PORT: "5432"
  AUTH_DB_USER: postgres
  AUTH_DB_NAME: safetrace_auth
  AUTH_DB_TIMEZONE: Asia/Kolkata
  KAFKA_BROKER: kafka:9092
  STATE: docker
  AUTH_DOCKER_ORIGIN: http://safetrace.local
  AUTH_DEV_ORIGIN: http://localhost:8080
