apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert
  template:
    metadata:
      labels:
        app: alert
    spec:
      containers:
        - name: alert
          image: jsndz/safetrace_alert:latest
          ports:
            - containerPort: 3003
          envFrom:
            - configMapRef:
                name: alert-config
            - secretRef:
                name: alert-secret
