apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert
  namespace: safetrace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alert
  template:
    metadata:
      labels:
        app: alert
    spec:
      containers:
        - name: alert
          image: jsndz/safetrace_alert:latest
          ports:
            - containerPort: 3003
          envFrom:
            - configMapRef:
                name: safetrace-config
            - secretRef:
                name: safetrace-secrets
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
