apiVersion: v1
kind: Service
metadata:
  name: alert-service
  namespace: safetrace
spec:
  selector:
    app: alert
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP
