apiVersion: apps/v1
kind: Deployment
metadata:
  name: geo-fencer
  namespace: safetrace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: geo-fencer
  template:
    metadata:
      labels:
        app: geo-fencer
    spec:
      containers:
        - name: geo-fencer
          image: jsndz/safetrace_geo-fencer:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          ports:
            - containerPort: 3001
