apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: safetrace-cluster
  namespace: safetrace
spec:
  kafka:
    version: 4.1.0
    config:
      process.roles: broker,controller
      node.id: 0
      inter.broker.listener.name: internal
      listener.security.protocol.map: internal:PLAINTEXT,external:PLAINTEXT
      controller.quorum.voters: 0@safetrace-cluster-kafka-0.safetrace-cluster-kafka-brokers.safetrace.svc:9093
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      group.initial.rebalance.delay.ms: 0
      auto.create.topics.enable: true
    listeners:
      - name: internal
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: nodeport
        tls: false
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: safetrace-pool
  namespace: safetrace
  labels:
    strimzi.io/cluster: safetrace-cluster
spec:
  replicas: 1
  roles:
    - broker
    - controller
  storage:
    type: ephemeral
