apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: safetrace
  labels:
    app: kafka
spec:
  serviceName: kafka
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      securityContext:
        fsGroup: 0
      containers:
        - name: kafka
          image: doughgle/kafka-kraft
          ports:
            - containerPort: 9092 # broker port
            - containerPort: 9093 # controller port
          env:
            # --- KRaft cluster configs ---
            - name: KAFKA_ENABLE_KRAFT
              value: "yes"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CFG_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://$(HOSTNAME).kafka.safetrace.svc.cluster.local:9092"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "0@kafka-0.kafka.safetrace.svc.cluster.local:9093,1@kafka-1.kafka.safetrace.svc"
