apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-logger
  namespace: safetrace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: location-logger
  template:
    metadata:
      labels:
        app: location-logger
    spec:
      containers:
        - name: location-logger
          image: jsndz/safetrace_location-logger:latest
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: safetrace-config
            - secretRef:
                name: safetrace-secrets
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
