apiVersion: v1
kind: Secret
metadata:
  name: safetrace-secrets
  namespace: safetrace
  labels:
    app: safetrace
type: Opaque
stringData:
  JWT_SECRET: "safetraceisabsolutely"

  AUTH_DB_HOST: "auth-db"
  AUTH_DB_PORT: "5432"
  AUTH_DB_USER: "postgres"
  AUTH_DB_PASSWORD: "safetrace"
  AUTH_DB_NAME: "safetrace_auth"
  AUTH_DB_TIMEZONE: "Asia/Kolkata"

  FENCER_DB_HOST: "fencer-db"
  FENCER_DB_PORT: "5432"
  FENCER_DB_USER: "postgres"
  FENCER_DB_PASSWORD: "safetrace"
  FENCER_DB_NAME: "safetrace_fencer"
  FENCER_DB_TIMEZONE: "Asia/Kolkata"
