apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: safetrace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: jsndz/safetrace_server:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: safetrace-config
            - secretRef:
                name: safetrace-secrets
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
