apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: fencer-pgdata
  name: fencer-pgdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
