apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: alert
  name: alert
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: alert
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: alert
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: env
          image: alert
          name: alert
          ports:
            - containerPort: 3003
              protocol: TCP
      restartPolicy: Always
