apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: geo-fencer
  name: geo-fencer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: geo-fencer
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: geo-fencer
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: env
          image: geo-fencer
          name: geo-fencer
          ports:
            - containerPort: 3002
              protocol: TCP
      restartPolicy: Always
